TestCam/Controllers/VisitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestCam.Models;
using System.Data;
using System.IO;
using System.Configuration;
using System.Data.SqlClient;


namespace TestCam.Controllers
{
    public class VisitorController : Controller
    {
        TestCamEntities db = new TestCamEntities();

        [HttpGet]
        public ActionResult VisitorIndex()
        {
            Session["CapturedImage"] = "";
            tbl_Personal personal = new tbl_Personal();
            var lastVisitorPassNumber = db.tbl_Personal.OrderByDescending(c => c.ID).FirstOrDefault();
            var date  = DateTime.Now.ToString("yyyy");
            if (lastVisitorPassNumber == null)
            {
                personal.VisitorPassNumber = "NCSPUN" + Convert.ToString(date) + "1" ;
            }
            else
            {
                personal.VisitorPassNumber = "NCSPUN" + (Convert.ToString(date) + lastVisitorPassNumber.ID);
            }
            return View(personal);
        }

        [HttpPost]
        public ContentResult GetCapture()
        {
            string url = Session["CapturedImage"].ToString();
            //Session["CapturedImage"] = null;
            return Content(url);
        }


        [HttpPost]
        public ActionResult Capture()
        {

            if (Request.InputStream.Length > 0)
            {
                using (StreamReader reader = new StreamReader(Request.InputStream))
                {
                    string hexString = Server.UrlEncode(reader.ReadToEnd());
                    string imageName = DateTime.Now.ToString("dd-MM-yy hh-mm-ss");
                    string imagePath = string.Format("~/VisitorImage/{0}.png", imageName);
                    System.IO.File.WriteAllBytes(Server.MapPath(imagePath), ConvertHexToBytes(hexString));
                    Session["CapturedImage"] = VirtualPathUtility.ToAbsolute(imagePath);
                }
            }

            return View();
        }

        private static byte[] ConvertHexToBytes(string hex)
        {
            byte[] bytes = new byte[hex.Length / 2];
            for (int i = 0; i < hex.Length; i += 2)
            {
                bytes[i / 2] = Convert.ToByte(hex.Substring(i, 2), 16);
            }
            return bytes;
        }

        [HttpPost]
        public ActionResult VisitorIndex(TestCam.Models.tbl_Personal model)
        {
            if (ModelState.IsValid)
            {
                model.ImagePath = Session["CapturedImage"].ToString();
                db.tbl_Personal.Add(model);
                db.SaveChanges();
                TempData["Success"] = "Visitor added Successfully!";
              //  return RedirectToAction("VisitorIndex");
            }
            return Json(model);
           // return View(model);
        }

        //Visitor's List
        [HttpGet]
        public ActionResult VisitorList()
        {
            GetListItems();
            return View();
        }


        public void GetListItems()
        {
            var result = db.tbl_Personal.ToList();
            ViewBag.VisitorList = result;
        }

        //Edit Visitor
        [HttpGet]
        public ActionResult VisitorEdit(int Id)
        {
            var std = db.tbl_Personal.Where(s => s.ID == Id).FirstOrDefault();
            return View(std);
        }
    }
}

TestCam/Views/Visitor/VisitorEdit.cshtml
@model TestCam.Models.tbl_Personal

@{
    ViewBag.Title = "VisitorEdit";
}

@section scripts
{
    @*<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>*@
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/jquery.webcam.js"></script>
    <script src="~/Scripts/visitor.js"></script>
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
}
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
         {
             Text = "Gate 01 - RECEPTION",
             Value = "Gate 01 - RECEPTION"
         });
    listItems.Add(new SelectListItem
         {
             Text = "Gate 02 - RECEPITON",
             Value = "Gate 02 - RECEPITON",
             Selected = true
         });
    listItems.Add(new SelectListItem
         {
             Text = "Gate 03 - RECEPITON ",
             Value = "Gate 03 - RECEPITON"
         });
}

@using (Html.BeginForm("VisitorIndex", "Visitor", FormMethod.Post, new { @class = "m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" }))
{


    @Html.AntiForgeryToken()
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        Edit Visitor
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->

        <div class="m-grid m-grid--hor m-grid--root m-page">
            <div class="m-form__section m-form__section--first">
                @*<div class="form-group m-form__group">
                    <table border="0" cellpadding="0" cellspacing="0">
                        <tr>
                            <td><div id="webcam"></div></td>
                            <td>&nbsp;</td>
                            <td><img id="imgCapture" style="visibility: hidden; width: 200px;height: 200px" /></td>
                        </tr>
                    </table>
                    <br />
                    <input type="button" value="Capture" onclick="Capture();" />
                    <br />
                </div>*@
                <div class="form-group m-form__group">
                    @Html.Label("Visitor Pass :")
                    @Html.DisplayFor(m => m.VisitorPassNumber, new { htmlAttributes = new { @class = "form-control m-input" } })
                    @Html.HiddenFor(m => m.VisitorPassNumber)
                    @Html.ValidationMessageFor(m => m.VisitorPassNumber)
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("Gate Number :")
                    @Html.DropDownListFor(m => m.GateNumber, listItems, "-- Select Gate Number --", new { htmlAttributes = new { @class = "form-control m-input" } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("Name :")
                    @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter Your Name " } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("To Meet :")
                    @Html.EditorFor(m => m.ToMeet, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter Concern Person Name" } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("From :")
                    @Html.EditorFor(m => m.FromWhere, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter your office location" } })
                </div>

                @*<div class="m-form__section m-form__section--first">*@
                <div class="form-group m-form__group">
                    @Html.Label("Purpose :")
                    @Html.EditorFor(m => m.Purpose, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter purpose " } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("In Time :")
                    @Html.EditorFor(m => m.Date, new { htmlAttributes = new { @class = "form-control m-input", placeholder = "visitor's Gate Pass Date", @readonly = "true" } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("Valid UpTo :")
                    @Html.EditorFor(m => m.ValidUpTo, new { htmlAttributes = new { @class = "form-control m-input", placeholder = "visitor's Gate Pass End Date", @readonly = "true" } })
                </div>
            </div>
            @*</div>*@
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-8">
                        <button type="submit" class="btn btn-primary">
                            Submit
                        </button>
                        <button type="reset" class="btn btn-secondary">
                            Cancel
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <!--end::Form-->
    </div>

}

TestCam/Views/Visitor/VisitorIndex.cshtml
@{
    ViewBag.Title = "VisitorIndex";
}
@model TestCam.Models.tbl_Personal

@if (TempData["Success"] != null)
{
    <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
}
@section scripts
{
    @*<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>*@
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/jquery.webcam.js"></script>
    <script src="~/Scripts/visitor.js"></script>
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
}
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
         {
             Text = "Gate 01 - RECEPTION",
             Value = "Gate 01 - RECEPTION"
         });
    listItems.Add(new SelectListItem
         {
             Text = "Gate 02 - RECEPITON",
             Value = "Gate 02 - RECEPITON",
             Selected = true
         });
    listItems.Add(new SelectListItem
         {
             Text = "Gate 03 - RECEPITON ",
             Value = "Gate 03 - RECEPITON"
         });
}

@using (Html.BeginForm("VisitorIndex", "Visitor", FormMethod.Post, new { @class = "m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed",  id="visitorForm" }))
{


    @Html.AntiForgeryToken()
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <span class="m-portlet__head-icon m--hide">
                        <i class="la la-gear"></i>
                    </span>
                    <h3 class="m-portlet__head-text">
                        New Visitor
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->

        <div class="m-grid m-grid--hor m-grid--root m-page">
            <div class="m-form__section m-form__section--first">
                <div class="form-group m-form__group">
                    @*<table border="0" cellpadding="0" cellspacing="0">
                        <tr>
                            <td>*@
                    <div id="webcam"></div>
                            @*</td>
                            <td>&nbsp;</td>*@
                            @*<td>*@
                            @*<img id="imgCapture" style="visibility: hidden; width: 200px;height: 200px" />*@@*</td>*@
                        @*</tr>
                    </table>*@
                    <br />
                    <input type="button" value="Capture" onclick="Capture();" />
                    <br />
                </div>

                <div class="form-group m-form__group">
                    @Html.Label("Visitor Pass :")
                    @Html.DisplayFor(m => m.VisitorPassNumber, new { htmlAttributes = new { @class = "form-control m-input" } })
                    @Html.HiddenFor(m => m.VisitorPassNumber)
                    @Html.ValidationMessageFor(m => m.VisitorPassNumber)
                </div>

                <div class="form-group m-form__group">
                    @Html.Label("Gate Number :")
                    @Html.DropDownListFor(m => m.GateNumber, listItems, "-- Select Gate Number --", new { htmlAttributes = new { @class = "form-control m-input" } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("Name :")
                    @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter Your Name " } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("Mobile No :")
                    @Html.EditorFor(m => m.MobileNo, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter Mobile Number " } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("Email :")
                    @Html.EditorFor(m => m.Email, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter an Email " } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("To Meet :")
                    @Html.EditorFor(m => m.ToMeet, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter Concern Person Name" } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("From :")
                    @Html.EditorFor(m => m.FromWhere, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter your office location" } })
                </div>

                @*<div class="m-form__section m-form__section--first">*@
                <div class="form-group m-form__group">
                    @Html.Label("Purpose :")
                    @Html.EditorFor(m => m.Purpose, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter purpose " } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("Assets :")
                    @Html.EditorFor(m => m.Asset, new { htmlAttributes = new { @class = "form-control m-input", @placeholder = "Enter Assests details " } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("In Time :")
                    @Html.EditorFor(m => m.Date, new { htmlAttributes = new { @class = "form-control m-input", placeholder = "visitor's Gate Pass Date", @readonly = "true", @id = "m_datetimepicker_2" } })
                </div>
                <div class="form-group m-form__group">
                    @Html.Label("Valid UpTo :")
                    @Html.EditorFor(m => m.ValidUpTo, new { htmlAttributes = new { @class = "form-control m-input", placeholder = "visitor's Gate Pass End Date", @readonly = "true" } })
                </div>
            </div>
            @*</div>*@
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-8">
                        <input type="button" class="btn btn-primary" value="Submit & Print" onclick="submitAndPrint();" /> 
                        <button type="reset" class="btn btn-secondary" onclick="Cancel();">
                            Cancel
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <!--end::Form-->
    </div>

}

<div class="row  align-items-center" id="printPage" style="width:50%">
    <div class=" col">
    <div class="m-widget14__legend">

        <span class="m-widget14__legend-text" id="printName"></span>
    </div>
    <div class="m-widget14__legend">
        <span class="m-widget14__legend-text" id="printContact"></span>
    </div>
    <div>
        <img style="height: 200px;width:200px" id="printImage" />
    </div>


</div>
    <div class="col">
        <div class="m-widget14__legends">
            <div class="m-widget14__legend">
                @Html.Label("Gate Number :")
                <span class="m-widget14__legend-text" id="printGateNumber"></span>
            </div>
            <div class="m-widget14__legend">
                @Html.Label("Purpose :")
                <span class="m-widget14__legend-text" id="printPurpose"></span>
            </div>
            <div class="m-widget14__legend">
                @Html.Label("To Meet :")
                <span class="m-widget14__legend-text" id="printToMeet"></span>
            </div>
            <div class="m-widget14__legend">
                @Html.Label("In Time :")
                <span class="m-widget14__legend-text" id="printDate"></span>
            </div>
            <div class="m-widget14__legend">
                @Html.Label("Valid UpTo :")
                <span class="m-widget14__legend-text" id="printValidUpTo"></span>
            </div>
        </div>
    </div>
</div>

TestCam/Views/Visitor/VisitorList.cshtml
@model IEnumerable<TestCam.Models.tbl_Personal>

@{
    ViewBag.Title = "VisitorList";
}
var imagePath = @Model.;
<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    Visitor's List
                </h3>
            </div>
        </div>

    </div>
    <div class="m-portlet__body">
        <table class="table table-striped- table-bordered table-hover table-checkable" id="Visitors">
            <thead>
                <tr>
                    <th>@Html.Label("Name")</th>
                    <th>@Html.Label("Purpose")</th>
                    <th>@Html.Label("Meet")</th>
                    <th>@Html.Label("From")</th>
                    <th>@Html.Label("In Time")</th>
                    <th>@Html.Label("Gate No")</th>
                    <th>@Html.Label("Pass No")</th>
                    <th>@Html.Label("Valid UpTo")</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.VisitorList)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Purpose</td>
                        <td>@item.ToMeet</td>
                        <td>@item.FromWhere</td>
                        <td>@item.Date</td>
                        <td>@item.GateNumber</td>
                        <td>@item.VisitorPassNumber</td>
                        <td>@item.ValidUpTo</td>

                        @*<td>@Html.ActionLink("Details", "VisitorEdit", "Visitor", new { id = item.ID })</td>*@
                        <td>@Html.ActionLink("Details", "VisitorEdit", new { id = item.ID })</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>