TestCam/Controllers/Visitor1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestCam.Models;
using System.Data;
using System.IO;


namespace TestCam.Controllers
{
    public class Visitor1Controller : Controller
    {
        [HttpGet]
        public ActionResult VisitorIndex1()
        {
            return View();
        }
        [HttpPost]
        public ActionResult VisitorIndex1(string base64image)
        {
            if (!String.IsNullOrEmpty(base64image))
            {
                //Maybe we should  remove unnecessary string input in front of the value
                string pictureObj = base64image.Replace("data:image/png;base64,", String.Empty);

                var model = new tbl_Picture();
                model.Picture = System.Convert.FromBase64String(pictureObj);

                //And then you can insert the model into db. 
            }
            return Json(new { result = 1 });
        }
    }   
}

TestCam/Views/Visitor1/VisitorIndex1.cshtml
@{
    ViewBag.Title = "VisitorIndex1";
}

<h2>VisitorIndex1</h2>

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="~/Scripts/jquery.webcam.js"></script>

<script language="text/JavaScript">
    
    webcam.set({
        width: 320,
        height: 240,
        image_format: 'jpeg',
        jpeg_quality: 90
    });
    webcam.attach( '#my_camera' );
    
    function Capture() {
        webcam.capture();   
    }
    
    //function take_snapshot() {
    //       webcam.snap( function(data_uri) {
    //           document.getElementById('results').innerHTML =
    //           '<img id="base64image" src="' + data_uri + '"/>';
    //       } );
    //   }
    
    $(function(){
        $('#btnCapture').on('click', function(){
            var file = document.getElementById("base64image").src;
            $.ajax({  
                type: "POST",  
                url: '/Visitor1/VisitorIndex1',  
                data: { base64image: file },  
                dataType: "json",  
                contentType: "application/json; charset=utf-8",  
                success: function () {
                    alert("Success!!");
                    //$('#myModal3').modal('hide'); //hide the modal
                },  
                error: function () {  
                    alert("Error while inserting data");  
                }  
            });  
        });
    });
   
    
</script>




@*@using (Html.BeginForm("VisitorIndex1", "Visitor1", FormMethod.Post))
{
    @Html.AntiForgeryToken()*@
    @*<div class="modal-body">
        <div class="row">*@
            <input type="text" name="franid" id="franid" value="" class="hidden" />
            <div id="my_camera" class="col-lg-6"></div>
            <div id="results" class="col-lg-6">Your captured image will appear here...</div>
        @*</div>*@
        <form>
            <input type="button" value="Capture" onclick="Capture();" />
        </form>
    @*</div>*@
    @*<div class="modal-footer">
        <center>
            <button class="btn btn-success" type="button" id="btnCapture">Submit</button>
            <button class="btn" type="button" data-dismiss="modal">Close</button>
        </center>
    </div>*@
@*}*@